<?php

// @codingStandardsIgnoreFile

// @TODO MAKE THIS SHIT BEAUTIFUL, ADD CSS MAYBE
/**
 * Product view template
 *
 * @var $block \Onilab\CartPopup\Block\CartPopup\Options
 */
?>
<?php $helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
<?php $product = $block->getProduct(); ?>
<?php $image = 'category_page_grid'; ?>

<div class="cart-popup-swatch-image">
    <a href="<?= $block->escapeUrl($block->getProductUrl($product)) ?>" class="product-item__photo-link">
        <?= $block->getImage($product, $image)->toHtml() ?>
    </a>
</div>

<?= $block->getChildHtml('product.info.main') ?>

<div class="product-add-form">
    <form data-product-sku="<?= $block->escapeHtml($product->getSku()) ?>"
          action="<?= /* @NoEscape */ $block->getSubmitUrl($product) ?>" method="post"
          id="product_addtocart_form"<?php if ($product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $product->getId() ?>" />
        <input type="hidden" name="selected_configurable_option" value="" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
        <input type="hidden" name="item"  value="<?= /* @noEscape */ $block->getRequest()->getParam('id') ?>" />
        <input type="hidden" name="form_key" value="<?= $block->getFormKey() ?>"/>
        <?= $block->getChildHtml('form_top') ?>

        <?php if (!$block->hasOptions()):?>
            <?= $block->getChildHtml('product_info_form_content') ?>
        <?php else:?>
            <?php if ($product->isSaleable()):?>
                <?= $block->getChildChildHtml('options_container') ?>
            <?php endif;?>
        <?php endif; ?>

        <?= $block->getChildHtml('form_bottom') ?>
    </form>
</div>
<script>
    require([
        'jquery',
        'priceBox'
    ], function($){
        var dataPriceBoxSelector = '.cart-popup [data-role=priceBox]',
            dataProductIdSelector = '[data-product-id=<?= $block->escapeHtml($product->getId()) ?>]',
            priceBoxes = $(dataPriceBoxSelector + dataProductIdSelector);

        priceBoxes = priceBoxes.filter(function(index, elem){
            return !$(elem).find('.price-from').length;
        });

        priceBoxes.priceBox({'priceConfig': <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>});
    });
</script>
